[package]
name = "hampi"
version = "0.1.0"
authors = ["gabhijit"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0" }


[[bin]]
name = "tokenize-asn"
path = "src/bin/tokenize-asn.rs"
